dictionary = {
    'crimes': [
        'Abduction', 'Abuse', 'Accessory', 'Accomplice', 'Accused', 'Accuser', 'Acquittal',
        'Activists', 'Adversary', 'Affect', 'AFIS', 'Against', 'Agency', 'Aggravated assault',
        'Alarm', 'Alcohol', 'Alert', 'Alias', 'Alibi', 'Alienate', 'Allegation', 'Ammunition', 'APB', 'Appeal',
        'Apprehension', 'Armed', 'Arraignment', 'Arrest', 'Arsenal', 'Arson', 'Art forgery', 'Assailant', 'Assault',
        'At large', 'Attack', 'Authority', 'Autopsy', 'Background check', 'Backup', 'Bail', 'Ballistics', 'Bandit',
        'Battery', 'Beat', 'Behavior', 'Behind bars', 'Belligerence', 'Big house', 'Blackmail', 'Bloodstain', 'Bombing',
        'Brawl', 'Breach', 'Break-in', 'Breaking and entering', 'Bribery', 'Brigand', 'Brutality', 'Bullying',
        'Burden of proof', 'Burglary', 'Bystander', 'Capture', 'Case', 'Cat burglar', 'Caution', 'Chase', 'Cheat',
        'Civil', 'Claim', 'Coercion', 'Collar', 'Collusion', 'Combat', 'Commission', 'Commit', 'Complaint', 'Complication',
        'Con artist', 'Conceal', 'Condemn', 'Conduct', 'Confession', 'Conflict', 'Connection', 'Conspiracy', 'Contact',
        'Contempt', 'Control', 'Controversial', 'Conviction', 'Cops', 'Coroner', 'Correctional institution', 'Corruption',
        'Counsel', 'Counterfeit', 'Court', 'Credit theft', 'Crime', 'Criminal', 'Criminal justice system', 'Criminology', 'Crook',
        'Cuffs', 'Custody', 'Damage', 'Danger', 'Dangerous', 'Dark side', 'Data base', 'Deadly', 'Deal', 'Dealings',
        'Death', 'Deed', 'Defendant', 'Defense', 'Deliberate', 'Delinquency', 'Democratic', 'Denial', 'Department',
        'Deputy', 'Detail', 'Detain', 'Detection', 'Detective', 'Detention', 'Deter', 'Determination', 'Deviant',
        'Direct', 'Discovery', 'Dismember', 'Disobedience', 'Disorderly', 'Dispatch', 'Disregard', 'Disruption',
        'District attorney', 'DNA', 'Documentation', 'Documents', 'Domestic', 'Dossier', 'Dragnet. fingerprints',
        'Drill', 'Drugs', 'Duty', 'Educate', 'Education', 'Effect', 'Elusive', 'Embezzle', 'Emergency', 'Enable',
        'Encumber', 'Endangerment', 'Enforce', 'Entail', 'Entrapment', 'Equality', 'Escape', 'Ethical', 'Evasive',
        'Eviction', 'Evidence', 'Evil', 'Examination', 'Execute', 'Exonerate', 'Expert', 'Explosives', 'Expunge',
        'Extort', 'Extortion', 'Extradite', 'Extradition', 'Extreme', 'Eye witness', 'Failure', 'Fairness', 'Falsehood',
        'Family', 'Fatality', 'Fault', 'FBI', 'Federal', 'Felony', 'Fence', 'Ferocity', 'Fight', 'Fighting', 'Fine',
        'Fingerprint', 'Firebombing', 'First-degree', 'Flee', 'Flight', 'Footprints', 'Forbidden', 'Force', 'Forensics',
        'Forgery', 'Formal charge', 'Frantic', 'Fraud', 'Freedom', 'Frisk', 'Full-scale', 'Fundamental', 'Furtive',
        'Gang', 'Gangster', 'Good guys', 'Gory', 'Government', 'Grief', 'Grievance', 'Guarantee', 'Guard', 'Guilty',
        'Gun', 'Gunrunning', 'Hand-to-hand', 'Handcuffed', 'Handcuffs', 'Handle', 'Harassment', 'Harm', 'Harmful',
        'Headquarters', 'Hearsay', 'Heinous', 'Helicopter', 'Help', 'Helpful', 'High-powered rifle', 'High-profile',
        'Hijack', 'Hire', 'Hit man', 'Holding cell', 'Holster', 'Homicide', 'Honesty', 'Honor', 'Hooligan', 'Hostage',
        'Hot-line', 'Humanity', 'Identification', 'Illegal', 'Immoral', 'Immunity', 'Impeach', 'Impersonation', 'Impression',
        'Imprison', 'Imprisonment', 'Improper', 'Incarcerate', 'Incarceration', 'Incompetent', 'Incriminate', 'Incriminating',
        'Indictment', 'Influence', 'Informant', 'Information', 'Infringe', 'Initiative', 'Injury', 'Inmate', 'Innocence',
        'Innocent', 'Inquest', 'Instruct', 'Integrity', 'Intelligence', 'Interests', 'Interference', 'International',
        'Interpol', 'Interpretation', 'Interrogate', 'Interstate', 'Intervention', 'Interview', 'Intrastate', 'Intruder',
        'Invasive', 'Investigate', 'Investigation', 'Irregular', 'Irresponsible', 'Issue', 'Jacket', 'Jail', 'John Doe',
        'Judge', 'Judgment', 'Judicial', 'Judiciary', 'Jurisdiction', 'Jury', 'Jury tampering', 'Justice', 'Juvenile',
        'Kidnapping', 'Kill', 'Killer', 'Kin', 'Larceny', 'Law', 'Law-abiding', 'Lawfully', 'Lawless', 'Lawsuit', 'Lawyer',
        'Leaks', 'Lease', 'Legal', 'Legislation', 'Legitimate', 'Lethal', 'Liability', 'Libel', 'Liberty', 'License',
        'Lie detector', 'Lie detector test', 'Lien', 'Lieutenant', 'Limits', 'Line up', 'Loan shark', 'Long hours', 'Lowlife',
        'Loyalty', 'Lynch', 'Mace', 'Maintain', 'Majority', 'Malfeasance', 'Malice', 'Malicious', 'Malpractice', 'Manacled',
        'Manhunt', 'Manslaughter', 'Marshal', 'Mayhem', 'Men', 'Metal detector', 'Minor', 'Minority', 'Miscreant',
        'Misdemeanor', 'Missing person', 'Mission', 'Model', 'Money laundering', 'Moratorium', 'Motorist', 'Mugger',
        'Murder', 'Murderer', 'Nab', 'National', 'Negligence', 'Negligent', 'Negotiable', 'Negotiate', 'Neighborhood',
        'Network', 'Nine-one-one', 'Notation', 'Notification', 'Nuisance', 'Oath', 'Obey', 'Obligation', 'Obscenity',
        'Offender', 'Offense', 'Officer', 'Official', 'On-going', 'Open case', 'Opinion', 'Opportunity', 'Order',
        'Organize', 'Ownership', 'Parole', 'Partner', 'Partnership', 'Pathology', 'Patrol', 'Pattern', 'Pedestrian',
        'Peeping Tom', 'Penalize', 'Penalty', 'Perjury', 'Perpetrator', 'Petition', 'Petty theft', 'Phony', 'Pickpocket',
        'Plainclothes officer', 'Plea', 'Plead', 'Police', 'Policy', 'Polygraph', 'Posse', 'Power', 'Precedent', 'Precinct',
        'Preliminary findings', 'Prevention', 'Principle', 'Prior', 'Prison', 'Prisoner', 'Private', 'Private eye',
        'Probable cause', 'Probation', 'Probation officer', 'Procedure', 'Professional', 'Profile', 'Prohibit', 'Proof',
        'Property', 'Prosecute', 'Prosecutor', 'Prostitution', 'Protection', 'Protocol', 'Provision', 'Prowler', 'Public',
        'Punishment', 'Quake', 'Qualification', 'Quality', 'Quantity', 'Quarrel', 'Quell', 'Question', 'Quickly', 'Quirk',
        'Quiver', 'Racketeering', 'Radar', 'Raid', 'Rank', 'Rape', 'Rap sheet', 'Reason', 'Reckless', 'Reckless endangerment',
        'Record', 'Recovery', 'Recruit', 'Redress', 'Reduction', 'Refute', 'Register', 'Regulations', 'Reinforcement',
        'Reject', 'Release', 'Repeal', 'Reported', 'Reports', 'Reprobate', 'Reputation', 'Requirement', 'Resist',
        'Resistance', 'Resisting arrest', 'Responsibility', 'Restitution', 'Restraining order', 'Restriction', 'Revenge',
        'Rights', 'Riot', 'Robbery', 'Rogue', 'Rough', 'Rules', 'Rulings', 'Rumble', 'Rumrunner', 'Sabotage', 'Safecracking',
        'Safeguard', 'Sanction', 'Scene', 'Scofflaw', 'Sealed record', 'Search', 'Search and rescue team', 'Secret',
        'Seize', 'Seizure', 'Selection', 'Sentence', 'Sergeant', 'Serial killer', 'Seriousness', 'Services',
        'Sex crimes', 'Shackles', 'Sheriff', 'Shooting', 'Shoplifting', 'Shyster', 'Sighting', 'Situation',
        'Skillful', 'Skipping bail', 'Slander', 'Slashing', 'Slaying', 'Smuggling', 'Solicit', 'Sorrow', 'Speculation',
        'Spying', 'Squad', 'Squatter', 'Stabbing', 'Stakeout', 'Stalking', 'Statue', 'Statute', 'Stealing',
        'Stigma', 'Stipulation', 'Stool pigeon', 'Subdue', 'Subpoena', 'Substantiate', 'Successful', 'Summons',
        'Supervise', 'Suppress', 'Surveillance', 'Survivor', 'Suspect', 'Suspected', 'Suspicion', 'Suspicious',
        'Sworn', 'System', 'Tactic', 'Task force', 'Terrorism', 'Testify', 'Testimony', 'Theft', 'Theft',
        'Threatening', 'Three-strikes law', 'Thwart', 'Tire-slashing', 'Torture', 'Toxicology', 'Trace',
        'Traffic', 'Trafficking', 'Tragedy', 'Transfer', 'Trauma', 'Treason', 'Treatment', 'Trespass', 'Trial', 'Trooper',
        'Trust', 'Unacceptable', 'Unauthorized', 'Unclaimed', 'Unconstitutional', 'Undercover', 'Underpaid',
        'Understaffed', 'Unexpected', 'Unharmed', 'Uniform', 'Unintentional', 'Unit', 'Unjust', 'Unknown', 'Unlawful',
        'Unsolved', 'Uphold', 'Usury', 'Vagrancy', 'Vandalism', 'Viable', 'Vice', 'Victim', 'Victimize', 'Victory',
        'Vigilance', 'Violate', 'Violation', 'Violence', 'Volunteer', 'Vow', 'Voyeurism', 'Vulnerable', 'Wanted poster', 'Ward',
        'Warning', 'Warped', 'Warrant', 'Watch', 'Weapon', 'Will', 'Wired', 'Wiretap', 'Wisdom', 'Witness', 'Women', 'Worse', 
        'Wrong', 'Youth', 'Zeal', 'Zealous'
    ],
    'environment': [
        'climate', 'habitat', 'setting', 'surroundings', 'ambiance',
        'backdrop', 'background', 'circumstances', 'element', 'encompassment',
        'entourage', 'jungle', 'locale', 'milieu', 'neighborhood', 'purlieus',
        'terrain', 'territory', 'turf', 'neck of the woods', 'stomping ground'
    ],
    'families': [
        'Abilities', 'Accommodation', 'Activity', 'Adolescence', 'Adoption', 'Adult', 'Advice', 'Advise', 'Affection', 'Affinity', 'Alimony', 'Allegiance', 'Ancestor', 'Anger', 'Anniversary', 'Antagonism', 'Anxiety', 'Appreciation', 'Approval', 'Ardent', 'Association', 'Attentive', 'Aunt', 'Authority', 'Bachelor', 'Banns', 'Baptism', 'Bar mitzvah', 'Bat mitzvah', 'Betroth', 'Bloodline', 'Bonds', 'Bone fide', 'Breadwinner', 'Bride', 'Brotherly', 'Care', 'Care-giver', 'Celibate', 'Cherish', 'Child', 'Childhood', 'Children', 'Chores', 'Civility', 'Clan', 'Close-knit', 'Coaching', 'Cohort', 'Comfortable', 'Commitment', 'Commonality', 'Communicative', 'Community', 'Compassion', 'Compatibility', 'Competitive', 'Concern', 'Confidence', 'Congenial', 'Conjugal', 'Connection', 'Consideration', 'Constancy', 'Convivial', 'Couple', 'Courteous', 'Cousin', 'Custody', 'Daughter', 'Death', 'Decency', 'Defend', 'Deferential', 'Dependable', 'Descent', 'Determination', 'Development', 'Devotion', 'Differences', 'Discipline', 'Distance', 'Distant', 'Diverse', 'Divorce', 'Dowry', 'Dynamics', 'Earnest', 'Elderly', 'Eligible', 'Emotional', 'Empathy', 'Encouragement', 'Endearing', 'Engaged', 'Esteem', 'Estrangement', 'Everlasting', 'Fair', 'Faithful', 'Family', 'Father', 'Favoritism', 'Feelings', 'Fidelity', 'Flexibility', 'Folks', 'Forebear', 'Forgiveness', 'Foster child', 'Foundation', 'Fraternal', 'Fraternal', 'Fretful', 'Friends', 'Friendship', 'Genealogy', 'Generation', 'Generosity', 'Genes', 'Genuine', 'Geriatric', 'Gestation', 'Grandparent', 'Grateful', 'Gratitude', 'Groom', 'Group', 'Grownup', 'Guardian', 'Guidance', 'Healthy', 'Heir', 'Helpmate', 'Hereditary', 'Heritage', 'History', 'Honesty', 'Hopeful', 'Hostility', 'House guest', 'Humor', 'Husband', 'Idealism', 'Illness', 'In-law', 'Indifference', 'Industrious', 'Infancy', 'Inheritance', 'Inspiration', 'Instructive', 'Insulting', 'Integrity', 'Intuitive', 'Isolation', 'Jealousy', 'Jobs', 'Joy', 'Judgment', 'Jurisdiction', 'Just', 'Juvenile', 'Kin', 'Kindness', 'Kindred', 'Kinfolk', 'Kinship', 'Laughter', 'Legal', 'Lineage', 'Listener', 'Longevity', 'Loving', 'Loyalty', 'Maiden name', 'Majority', 'Marriage', 'Mate', 'Matriarch', 'Matrimony', 'Mature', 'Maturity', 'Memories', 'Mentoring', 'Minor', 'Mom', 'Monogamy', 'Morale', 'Morals', 'Mother', 'Natal', 'Neglectful', 'Nephew', 'Nest', 'Newlywed', 'Niece', 'Nuclear family', 'Nuisance', 'Nuptial', 'Nurture', 'Obedient', 'Obnoxious', 'Observant', 'Offspring', 'Open-minded', 'Optimism', 'Origin', 'Parent', 'Partiality', 'Partner', 'Paternity', 'Patience', 'Patriarch', 'People', 'Perceptive', 'Perseverance', 'Philosophic', 'Polite', 'Posterity', 'Pretentious', 'Principles', 'Progeny', 'Protection', 'Provider', 'Punishment', 'Quality', 'Quantity', 'Quiet', 'Race', 'Relation', 'Relationship', 'Reliability', 'Reliance', 'Religion', 'Resilience', 'Resolution of differences', 'Respect', 'Respect', 'Responsibility', 'Retirement', 'Safety', 'Security', 'Senior', 'Sensible', 'Sensitivity', 'Separation', 'Sharing', 'Shivaree', 'Sibling', 'Sickness', 'Similarities', 'Sincerity', 'Single', 'Sister', 'Sisterhood', 'Solidarity', 'Son', 'Soul mate', 'Spouse', 'Standard', 'Stepmother', 'Support', 'Surname', 'Sweet', 'Sympathetic', 'Tact', 'Teamwork', 'Tenderness', 'Thoughtfulness', 'Ties', 'Time together', 'Tolerant', 'Tradition', 'Trait', 'Tribe', 'Triplet troth', 'Trust', 'Trustworthy', 'Truthful', 'Twin', 'Uncle', 'Understanding', 'Unforgiving', 'Union', 'Unique', 'Unite', 'Unity', 'Upbringing', 'Vacation', 'Valuable', 'Values', 'Variety', 'Vigilance', 'Volunteer', 'Vow', 'Warmth', 'Watchful', 'Wedlock', 'Welcoming', 'Wife', 'Willingness', 'Wisdom', 'Wise', 'Work', 'Worry', 'Worthwhile', 'Worthy', 'Youngster', 'Youth', 'Zeal'
    ],
    'education': [
        'school', 'nursery school', 'primary school', 'secondary school',
        'state school', 'private school', 'independent school',
        'boarding school', 'sixth-form college', 'technical college',
        'vocational college', 'art college', 'teacher training college',
        'university', 'classroom', 'desk', 'blackboard', 'whiteboard', 'chalk',
        'marker', 'pen', 'pencil', 'exercise book', 'lesson', 'homework',
        'test', 'term', 'half term', 'class', 'reading', 'writing',
        'arithmetic', 'spelling', 'to read', 'to write', 'to spell',
        'to teach', 'head teacher', 'headmaster', 'headmistress', 'teacher',
        'pupil', 'head boy', 'head girl', 'prefect', 'school governor',
        'register', 'assembly', 'school holidays', 'school meals',
        'school dinners', 'computer room', 'cloakroom', 'changing room', 'gym',
        'playground', 'library', 'lecture hall', 'laboratory',
        'hall of residence', 'locker', 'playing field', 'sports hall',
        'professor', 'lecturer', 'researcher', 'research', 'undergraduate',
        'graduate', 'post-graduate', 'post-graduate student',
        'Masters student', 'PhD student', 'Master\'s degree',
        'Bachelor\'s degree', 'degree', 'thesis', 'dissertation', 'lecture',
        'debate', 'higher education', 'semester', 'student loan',
        'student union', 'tuition fees', 'university campus', 'exam',
        'to sit an exam', 'essay or paper', 'to fail an exam',
        'to pass an exam', 'to study', 'to learn', 'to revise', 'student',
        'curriculum', 'course', 'subject', 'grade', 'mark', 'exam results',
        'qualification', 'certificate', 'attendance', 'calculator',
        'projector', 'textbook', 'question', 'answer', 'mistake or error',
        'right or correct', 'wrong'
    ],
    'government': [
        'Account', 'Accountability', 'Advice', 'Advise', 'Affect', 'Aid', 'Aides', 'Amendment',
        'Anthem', 'Approval', 'Arms', 'Assembly', 'Assent', 'Aura', 'Authority', 'Average', 'Awe',
        'Balance', 'Bedrock', 'Belief', 'Bill of Rights', 'Bipartisan', 'Blunder', 'Boycott', 'Capital punishment',
        'Cause', 'Charisma', 'Charm', 'Citizenship', 'Civil', 'Civil rights', 'Clash', 'Cohesive',
        'Commander-in-chief', 'Concepts', 'Concession', 'Confirmation', 'Conflict', 'Congressional', 'Consequence',
        'Constituents', 'Constitution', 'Contempt', 'Control', 'Controversial', 'Cordiality', 'Culture',
        'Deadline', 'Death penalty', 'Debate', 'Decisive', 'Declaration of Independence', 'Delivery', 'Democracy',
        'Deter', 'Difference', 'Difficulty', 'Discontent', 'Discussion', 'Disrespect', 'Dissent', 'Distance',
        'District', 'Diversity', 'Donation', 'Due process', 'Effect', 'Employment', 'Enforcement', 'Equal',
        'Equality', 'Equation', 'Ethics', 'Evidence', 'Execution', 'Faction', 'Factual', 'Fateful', 'Flag', 'Foster',
        'Founding Fathers', 'Franchise', 'Freedom', 'Gamesmanship', 'Glory', 'Goals', 'Govern', 'Government',
        'Gracious', 'Greatness', 'Gun control', 'Happening', 'Happiness', 'Hearings', 'Heartland', 'Heritage',
        'Hopeful', 'Housing', 'Illegal', 'Implement', 'Independence', 'Innovate', 'Insight', 'Inspiring',
        'Integrity', 'Interest', 'Intrigue', 'Investigation', 'Issues', 'Joy', 'Judicial', 'Justice', 'Keen',
        'Kindness', 'Lasting', 'Law', 'Leader', 'Leadership', 'Legacy', 'Legislate', 'Liberty', 'Limitation',
        'Local level', 'Lofty', 'Mainstream', 'Measure', 'Mediate', 'Military', 'Militia', 'Monument', 'Moral',
        'Morale', 'Mortality', 'Nation', 'National', 'Need', 'Newspapers', 'Notable', 'Notification', 'Notorious',
        'Novice', 'Objective', 'Obstacle', 'Operate', 'Opinion', 'Opportunity', 'Option', 'Outpouring', 'Overcome',
        'Overhaul', 'Oversight', 'Parties', 'Partisan', 'Passage', 'Patient', 'Patriot', 'Patriotism', 'Peaceful',
        'Penalty', 'Perpetuity', 'Petition', 'Polarize', 'Politics', 'Pork belly', 'Power', 'Practice', 'Presidential',
        'Press', 'Pressure', 'Principal', 'Principles', 'Privacy', 'Protection', 'Protest', 'Provocative', 'Pursuit',
        'Qualm', 'Query', 'Question', 'Quick', 'Quid pro quo', 'Ratings', 'Reasoning', 'Recovery', 'Redistricting',
        'Regional', 'Religion', 'Resignation', 'Respect', 'Responsibility', 'Retaliation', 'Reverence', 'Revolutionary',
        'Rights', 'Rights', 'Rules', 'Secretive', 'Security', 'Separation of power', 'Social Security', 'Social service',
        'Solution', 'Speech', 'Spite', 'Standoff', 'Stars', 'State', 'Statue of Liberty', 'Stripes', 'Support',
        'Surveillance', 'Symbol', 'Threat', 'Timely', 'Tolerance', 'Tumult', 'Turnout', 'Unanimous', 'Understanding',
        'Unification', 'Unique', 'Unite', 'Unnecessary', 'Value', 'Vilify', 'Visionary', 'Vital', 'Volunteer', 'Vote',
        'War', 'Welfare', 'Windfall', 'Wisdom', 'Witness', 'Work', 'Youthful', 'Zeal', 'Zealous'
    ],
}
