dictionary = {
    'crimes': [
        'assault', 'blackmail', 'burglary', 'fraud', 'hijack', 'hooligan',
        'kidnapp', 'mugger', 'murderer', 'robber', 'shoplifter', 'smuggler',
        'terrorist', 'thief', 'vandal', 'appeal', 'barrister', 'caution',
        'cell', 'community service', 'court', 'court case', 'death penalty',
        'defense', 'fine', 'gaol', 'jail', 'guilty', 'imprisonment',
        'innocent', 'judge', 'jury', 'justice', 'lawyer', 'offence',
        'sentence', 'prison', 'probation', 'prosecution', 'punishment',
        'capital punishment', 'corporal punishment', 'remand home',
        'solicitor', 'trial', 'verdict', 'witness', 'arrest', 'ban',
        'break in', 'break out', 'break the law', 'burgle', 'charge',
        'commit a crime', 'escape', 'get away', 'get away with', 'hold up',
        'investigate', 'rob', 'steal', 'alibi', 'armed', 'burglar',
        'car alarm', 'alarm', 'legal', 'illegal', 'weapon'
    ],
    'environment': [
        'climate', 'habitat', 'setting', 'surroundings', 'ambiance',
        'backdrop', 'background', 'circumstances', 'element', 'encompassment',
        'entourage', 'jungle', 'locale', 'milieu', 'neighborhood', 'purlieus',
        'terrain', 'territory', 'turf', 'neck of the woods', 'stomping ground'
    ],
    'families': [
        'clan', 'folk', 'household', 'tribe', 'ancestors', 'ancestry', 'birth',
        'brood', 'children', 'descendants', 'descent', 'dynasty', 'forebears',
        'genealogy', 'generations', 'genrestarin-laws', 'inheritance',
        'kindred', 'lineage', 'parentage', 'pedigree', 'progenitors',
        'progeny', 'race', 'relations', 'relationship', 'relatives',
        'siblings', 'strain', 'starheirs and assignsstar', 'kith and kinstar',
        'menagestar'
    ],
    'education': [
        'school', 'nursery school', 'primary school', 'secondary school',
        'state school', 'private school', 'independent school',
        'boarding school', 'sixth-form college', 'technical college',
        'vocational college', 'art college', 'teacher training college',
        'university', 'classroom', 'desk', 'blackboard', 'whiteboard', 'chalk',
        'marker', 'pen', 'pencil', 'exercise book', 'lesson', 'homework',
        'test', 'term', 'half term', 'class', 'reading', 'writing',
        'arithmetic', 'spelling', 'to read', 'to write', 'to spell',
        'to teach', 'head teacher', 'headmaster', 'headmistress', 'teacher',
        'pupil', 'head boy', 'head girl', 'prefect', 'school governor',
        'register', 'assembly', 'school holidays', 'school meals',
        'school dinners', 'computer room', 'cloakroom', 'changing room', 'gym',
        'playground', 'library', 'lecture hall', 'laboratory',
        'hall of residence', 'locker', 'playing field', 'sports hall',
        'professor', 'lecturer', 'researcher', 'research', 'undergraduate',
        'graduate', 'post-graduate', 'post-graduate student',
        'Masters student', 'PhD student', 'Master\'s degree',
        'Bachelor\'s degree', 'degree', 'thesis', 'dissertation', 'lecture',
        'debate', 'higher education', 'semester', 'student loan',
        'student union', 'tuition fees', 'university campus', 'exam',
        'to sit an exam', 'essay or paper', 'to fail an exam',
        'to pass an exam', 'to study', 'to learn', 'to revise', 'student',
        'curriculum', 'course', 'subject', 'grade', 'mark', 'exam results',
        'qualification', 'certificate', 'attendance', 'calculator',
        'projector', 'textbook', 'question', 'answer', 'mistake or error',
        'right or correct', 'wrong'
    ],
    'government': [
        'Account', 'Accountability', 'Advice', 'Advise', 'Affect', 'Aid', 'Aides', 'Amendment',
        'Anthem', 'Approval', 'Arms', 'Assembly', 'Assent', 'Aura', 'Authority', 'Average', 'Awe',
        'Balance', 'Bedrock', 'Belief', 'Bill of Rights', 'Bipartisan', 'Blunder', 'Boycott', 'Capital punishment',
        'Cause', 'Charisma', 'Charm', 'Citizenship', 'Civil', 'Civil rights', 'Clash', 'Cohesive',
        'Commander-in-chief', 'Concepts', 'Concession', 'Confirmation', 'Conflict', 'Congressional', 'Consequence',
        'Constituents', 'Constitution', 'Contempt', 'Control', 'Controversial', 'Cordiality', 'Culture',
        'Deadline', 'Death penalty', 'Debate', 'Decisive', 'Declaration of Independence', 'Delivery', 'Democracy',
        'Deter', 'Difference', 'Difficulty', 'Discontent', 'Discussion', 'Disrespect', 'Dissent', 'Distance',
        'District', 'Diversity', 'Donation', 'Due process', 'Effect', 'Employment', 'Enforcement', 'Equal',
        'Equality', 'Equation', 'Ethics', 'Evidence', 'Execution', 'Faction', 'Factual', 'Fateful', 'Flag', 'Foster',
        'Founding Fathers', 'Franchise', 'Freedom', 'Gamesmanship', 'Glory', 'Goals', 'Govern', 'Government',
        'Gracious', 'Greatness', 'Gun control', 'Happening', 'Happiness', 'Hearings', 'Heartland', 'Heritage',
        'Hopeful', 'Housing', 'Illegal', 'Implement', 'Independence', 'Innovate', 'Insight', 'Inspiring',
        'Integrity', 'Interest', 'Intrigue', 'Investigation', 'Issues', 'Joy', 'Judicial', 'Justice', 'Keen',
        'Kindness', 'Lasting', 'Law', 'Leader', 'Leadership', 'Legacy', 'Legislate', 'Liberty', 'Limitation',
        'Local level', 'Lofty', 'Mainstream', 'Measure', 'Mediate', 'Military', 'Militia', 'Monument', 'Moral',
        'Morale', 'Mortality', 'Nation', 'National', 'Need', 'Newspapers', 'Notable', 'Notification', 'Notorious',
        'Novice', 'Objective', 'Obstacle', 'Operate', 'Opinion', 'Opportunity', 'Option', 'Outpouring', 'Overcome',
        'Overhaul', 'Oversight', 'Parties', 'Partisan', 'Passage', 'Patient', 'Patriot', 'Patriotism', 'Peaceful',
        'Penalty', 'Perpetuity', 'Petition', 'Polarize', 'Politics', 'Pork belly', 'Power', 'Practice', 'Presidential',
        'Press', 'Pressure', 'Principal', 'Principles', 'Privacy', 'Protection', 'Protest', 'Provocative', 'Pursuit',
        'Qualm', 'Query', 'Question', 'Quick', 'Quid pro quo', 'Ratings', 'Reasoning', 'Recovery', 'Redistricting',
        'Regional', 'Religion', 'Resignation', 'Respect', 'Responsibility', 'Retaliation', 'Reverence', 'Revolutionary',
        'Rights', 'Rights', 'Rules', 'Secretive', 'Security', 'Separation of power', 'Social Security', 'Social service',
        'Solution', 'Speech', 'Spite', 'Standoff', 'Stars', 'State', 'Statue of Liberty', 'Stripes', 'Support',
        'Surveillance', 'Symbol', 'Threat', 'Timely', 'Tolerance', 'Tumult', 'Turnout', 'Unanimous', 'Understanding',
        'Unification', 'Unique', 'Unite', 'Unnecessary', 'Value', 'Vilify', 'Visionary', 'Vital', 'Volunteer', 'Vote',
        'War', 'Welfare', 'Windfall', 'Wisdom', 'Witness', 'Work', 'Youthful', 'Zeal', 'Zealous'
    ],
}
